const SEARCH_PROPERTY = "SEARCH_PROPERTY";
const SET_PROPERTIES_DATA = "SET_PROPERTIES_DATA";
const SET_EQUIPMENT = "SET_EQUIPMENT";
const SET_HOMETYPE = "SET_HOMETYPE";
const SET_CONDITION = "SET_CONDITION";
const SET_TERRACE = "SET_TERRACE";
const SET_SWIMMING_POOL = "SET_SWIMMING_POOL";
const SET_PET_ALLOWED = "SET_PET_ALLOWED";
const SET_LIFT = "SET_LIFT";
const SET_AIR_CONDITIONING = "SET_AIR_CONDITIONING";
const SET_GARDEN = "SET_GARDEN";
const SET_BATH_ROOM = "SET_BATH_ROOM";
const SET_BED_ROOM = "SET_BED_ROOM";

export {
  SEARCH_PROPERTY,
  SET_PROPERTIES_DATA,
  SET_EQUIPMENT,
  SET_HOMETYPE,
  SET_CONDITION,
  SET_TERRACE,
  SET_SWIMMING_POOL,
  SET_PET_ALLOWED,
  SET_LIFT,
  SET_AIR_CONDITIONING,
  SET_GARDEN,
  SET_BATH_ROOM,
  SET_BED_ROOM,
};
